version: "3.8"

services:
  app:
    image: eendlabs/eh-pubsub
    build:
      context: ../
      dockerfile: ./build/package/app/Dockerfile
    depends_on:
      - pubsub_emulator
    environment:
      PUBSUB_EMULATOR_HOST: "pubsub_emulator:8793"
    volumes:
      - ../:/eventhorizon
    working_dir: /eventhorizon

  pubsub_emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:328.0.0-emulators
    ports:
      - "8793:8793"
    entrypoint:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - "--host-port=0.0.0.0:8793"